import React, { useEffect } from 'react';
import { TopBar } from '../../components/TopBar';
import { Footer } from '../../components/Footer';
import { useNavigate } from 'react-router-dom';

export default function PrivacyPage() {
    const navigate = useNavigate();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="min-h-screen flex flex-col font-body bg-white dark:bg-neutral-950 transition-colors duration-500 relative">
            <TopBar />

            <header className="sticky top-0 z-50 bg-slate-50/90 dark:bg-neutral-900/90 backdrop-blur-md border-b border-gray-200 dark:border-neutral-800 transition-all">
                <div className="max-w-[1600px] mx-auto px-4 md:px-8 h-16 md:h-20 flex items-center justify-between">
                    <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate('/')}>
                        <img src="/logo.jpg" alt="VendorFlow" className="h-8 md:h-10 w-auto rounded-lg" />
                        <span className="text-xl md:text-2xl font-bold font-heading text-emerald-700 dark:text-emerald-500 tracking-tight">
                            VendorFlow
                        </span>
                    </div>
                </div>
            </header>

            <main className="flex-grow max-w-[800px] mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
                <h1 className="text-4xl md:text-5xl font-bold font-heading text-gray-900 dark:text-white mb-8 tracking-tight">
                    Privacy Policy
                </h1>

                <div className="prose prose-lg dark:prose-invert prose-emerald max-w-none text-gray-600 dark:text-gray-300">
                    <p className="lead text-xl mb-8">
                        At VendorFlow, privacy and data security are the pillars of our curated marketplace ecosystem. We understand that high-volume merchants and end consumers trust us with sensitive information.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-12 mb-4">1. Information We Collect</h2>
                    <p className="mb-6">
                        We collect direct identifiers (such as names, addresses, and encrypted billing details) exclusively for the purpose of fulfilling enterprise accounts and processing customer orders securely. For analytics, we use PostHog to aggregate anonymized, high-level structural data on how our storefront tools perform in order to give targeted growth metrics back to our sellers.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-12 mb-4">2. Merchant Ownership of Data</h2>
                    <p className="mb-6">
                        If you are an approved VendorFlow merchant, your customer list remains strictly yours. We do not cross-market your customers to other brands within the ecosystem. The data generated by your storefront acts as an isolated silo accessible only via your secure dashboard.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-12 mb-4">3. Consumer Anonymity & Protection</h2>
                    <p className="mb-6">
                        For end consumers, your transaction metrics are shared securely with the specific merchant you engaged with upon checkout. We deploy military-grade encryption in transit (AES-256) and hold rigorous auditing standards so your shopping habits cannot be scraped or exploited by external ad registries.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-12 mb-4">4. Third-Party Disclosures</h2>
                    <p className="mb-6">
                        VendorFlow will never sell or rent consumer or merchant data logic streams to external data brokers. Disclosures are strictly limited to necessary infrastructural partners (such as Stripe for routing payments, and Supabase for database integrity) who adhere strictly strictly strictly to our security protocols.
                    </p>

                    <p className="text-sm mt-12 text-gray-500">Last Updated: February 2026</p>
                </div>
            </main>

            <div className="bg-[#1a202c]">
                <Footer
                    onLinkClick={(section, key) => {
                        if (section === 'legal') {
                            switch (key) {
                                case 'Terms & Conditions': navigate('/terms'); break;
                                case 'Privacy Policy': navigate('/privacy-policy'); break;
                                case 'Payment Policy': navigate('/payment-policy'); break;
                                case 'Cookie Policy': navigate('/cookie-policy'); break;
                            }
                        } else if (section === 'company') {
                            if (key === 'About Us') navigate('/about');
                            if (key === 'Contact Us') window.location.href = 'mailto:support@vendorflow.com';
                        }
                    }}
                    branding={{
                        storeName: "VendorFlow",
                        description: "The premier platform for ambitious independent brands and creators.",
                        socials: {
                            instagram: "https://www.instagram.com/_rajdeep.007_/",
                            twitter: "https://x.com/_rajdeep007_",
                            linkedin: "https://www.linkedin.com/in/rajdeep-bhattacharyya-497945371/"
                        }
                    }}
                    categories={[]}
                />
            </div>
        </div>
    );
}
