// Supabase Edge Function: invite-seller
// Deploy with: supabase functions deploy invite-seller

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { applyRateLimit } from '../_shared/rate-limiter.ts';

const corsHeaders = {
    'Access-Control-Allow-Origin': Deno.env.get('ALLOWED_ORIGIN') ?? 'https://venderflow.vercel.app',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
    // Handle CORS preflight
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    // Apply rate limiting (ADMIN level - 10 requests per minute)
    const rateLimitResponse = applyRateLimit(req, 'invite-seller', 'ADMIN');
    if (rateLimitResponse) {
        return rateLimitResponse;
    }

    try {
        // Get auth token from request
        const authHeader = req.headers.get('Authorization')
        if (!authHeader) {
            return new Response(
                JSON.stringify({ error: 'Missing authorization header' }),
                { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        // Create Supabase client with user's token
        const supabaseUrl = Deno.env.get('SUPABASE_URL')!
        const supabaseKey = Deno.env.get('SUPABASE_ANON_KEY')!
        const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

        const userClient = createClient(supabaseUrl, supabaseKey, {
            global: { headers: { Authorization: authHeader } }
        })

        // Verify caller is admin
        const { data: { user }, error: userError } = await userClient.auth.getUser()
        if (userError || !user) {
            return new Response(
                JSON.stringify({ error: 'Unauthorized' }),
                { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        const { data: profile } = await userClient
            .from('profiles')
            .select('role')
            .eq('id', user.id)
            .single()

        if (profile?.role !== 'admin') {
            return new Response(
                JSON.stringify({ error: 'Admin access required' }),
                { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        // Parse request body
        const { email, store_name, slug, plan } = await req.json()

        if (!email || !store_name || !slug) {
            return new Response(
                JSON.stringify({ error: 'Missing required fields: email, store_name, slug' }),
                { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        // Use service role client for db operations to bypass RLS and access restricted tables if needed
        const adminClient = createClient(supabaseUrl, serviceRoleKey)

        // 1. Check if email matches existing seller
        // Note: profiles use uuid, so we can't check profiles.id directly with email.
        // But we should check `auth.users`? We can't query auth.users directly easily without service key.
        // We can check `seller_invites` table.
        // For existing users, we assume email is unique in auth system, but Supabase doesn't expose `auth.users` search easily
        // via `from('users')`. `admin.listUsers` is possible but slow.
        // Ideally we check our own tables. `sellers` table usually has ID.
        // Let's just check `seller_invites` for duplicates.

        const { data: existingInvite } = await adminClient
            .from('seller_invites')
            .select('id')
            .or(`email.eq.${email},slug.eq.${slug}`)
            .maybeSingle()

        if (existingInvite) {
            return new Response(
                JSON.stringify({ error: 'An invite for this email or slug already exists' }),
                { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        const { data: existingSeller } = await adminClient
            .from('sellers')
            .select('id')
            .eq('slug', slug)
            .maybeSingle()

        if (existingSeller) {
            return new Response(
                JSON.stringify({ error: 'Store slug is already taken' }),
                { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        // 2. Create Invite Record
        const { data: invite, error: insertError } = await adminClient
            .from('seller_invites')
            .insert({
                email,
                store_name,
                slug,
                plan: plan || 'free',
                // token is auto-generated by default gen_random_uuid()
                // id is auto-generated
                // status default pending
            })
            .select()
            .single()

        if (insertError) {
            return new Response(
                JSON.stringify({ error: insertError.message }),
                { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
            )
        }

        // 3. Log the action
        await adminClient.from('audit_logs').insert({
            actor_id: user.id,
            action: 'seller_invited',
            target_type: 'seller_invite',
            target_id: invite.id,
            metadata: { email, store_name, slug, plan }
        })

        // 4. Return the Invite Link
        // For development/demo, we return the link.
        // Construct link: [origin]/register?token=[token]
        // We might not know origin here, so returning just the token path is safer.
        const origin = req.headers.get('origin') || 'http://localhost:5173';
        const inviteLink = `${origin}/register?token=${invite.token}`;

        return new Response(
            JSON.stringify({
                success: true,
                message: 'Invite created successfully',
                invite_link: inviteLink,
                token: invite.token
            }),
            { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )

    } catch (error) {
        console.error('Error:', error)
        return new Response(
            JSON.stringify({ error: 'Internal server error' }),
            { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
    }
})
