import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Premium Cotton Tee",
    price: 1999,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=2080&auto=format&fit=crop",
    description: "Crafted from 100% organic cotton, this premium tee offers breathable comfort and a tailored fit that retains its shape wash after wash. Perfect for layering or wearing on its own.",
    badge: { text: "Best Seller", bg: "bg-white/90", color: "text-gray-900" },
    rating: 5,
    reviews: 121,
    sizes: ["S", "M", "L"],
    category: "Men"
  },
  {
    id: 2,
    name: "Oxford Formal Shirt",
    price: 3499,
    originalPrice: 4999,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1888&auto=format&fit=crop",
    description: "A wardrobe staple, our Oxford shirt features a crisp finish, button-down collar, and a fit that transitions effortlessly from office to evening. Made with high-quality durable fabric.",
    badge: { text: "New", bg: "bg-primary/90", color: "text-white" },
    rating: 4.5,
    reviews: 45,
    sizes: ["M", "L", "XL"],
    category: "Men"
  },
  {
    id: 3,
    name: "Slim Fit Denim",
    price: 4499,
    originalPrice: 5999,
    image: "https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?q=80&w=2070&auto=format&fit=crop",
    description: "Engineered with a hint of stretch, these slim-fit jeans provide superior flexibility without compromising on the classic denim look. Features a classic 5-pocket styling and zip fly.",
    rating: 4.5,
    reviews: 89,
    sizes: ["30", "32", "34"],
    category: "Men"
  },
  {
    id: 4,
    name: "Lightweight Bomber",
    price: 5499,
    originalPrice: 7999,
    image: "https://images.unsplash.com/photo-1551028919-383718603bd5?q=80&w=1887&auto=format&fit=crop",
    description: "The perfect transitional piece. This lightweight bomber jacket features water-resistant fabric and a sleek, modern silhouette. Includes ribbed cuffs and hem for a snug fit.",
    badge: { text: "Trending", bg: "bg-accent/90", color: "text-white" },
    rating: 5,
    reviews: 210,
    sizes: ["S", "M", "L"],
    category: "Men"
  },
  {
    id: 5,
    name: "Floral Summer Dress",
    price: 2799,
    originalPrice: 3999,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1946&auto=format&fit=crop",
    description: "Embrace the season with this airy floral dress. Made from soft viscose, it drapes beautifully and features a flattering waist tie and adjustable straps.",
    rating: 4,
    reviews: 34,
    sizes: ["XS", "S", "M"],
    category: "Women"
  },
  {
    id: 6,
    name: "Fleece Hoodie",
    price: 2999,
    originalPrice: 4499,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=2070&auto=format&fit=crop",
    description: "Ultimate coziness meets street style. Our heavy-weight fleece hoodie keeps you warm with a soft brushed interior and durable construction. Available in multiple versatile colors.",
    badge: { text: "Best Seller", bg: "bg-white/90", color: "text-gray-900" },
    rating: 5,
    reviews: 512,
    sizes: ["S", "M", "L"],
    category: "Men"
  },
  {
    id: 7,
    name: "Classic Piqué Polo",
    price: 2199,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1625910515337-17d98d09517f?q=80&w=2070&auto=format&fit=crop",
    description: "Timeless style with a modern cut. This breathable piqué polo features a ribbed collar and cuffs for a structured yet comfortable look suitable for casual Fridays or weekend outings.",
    rating: 3.5,
    reviews: 76,
    sizes: ["M", "L", "XL"],
    category: "Men"
  },
  {
    id: 8,
    name: "Kids Comfort Tee",
    price: 999,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1519238263496-63e827bdcc3f?q=80&w=2073&auto=format&fit=crop",
    description: "Soft, durable, and ready for play. This kid-friendly tee is made from hypoallergenic fabric that's gentle on sensitive skin and withstands rough-and-tumble play dates.",
    badge: { text: "Eco Friendly", bg: "bg-primary/90", color: "text-white" },
    rating: 5,
    reviews: 98,
    sizes: ["S", "M", "L"],
    category: "Kids"
  },
  {
    id: 9,
    name: "Tailored Wool Blazer",
    price: 14999,
    originalPrice: 19999,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=2071&auto=format&fit=crop",
    description: "A sophisticated wool blazer featuring a modern slim cut. Perfect for business casual settings or elevating a weekend look with its textured finish and premium lining.",
    badge: { text: "Premium", bg: "bg-gray-900/90", color: "text-white" },
    rating: 4.8,
    reviews: 42,
    sizes: ["38", "40", "42", "44"],
    category: "Men"
  },
  {
    id: 10,
    name: "Classic Beige Trench",
    price: 9999,
    originalPrice: 12999,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1936&auto=format&fit=crop",
    description: "The quintessential trench coat. Water-resistant cotton gabardine construction with a double-breasted front and belted waist. A timeless addition to any wardrobe.",
    rating: 4.6,
    reviews: 88,
    sizes: ["XS", "S", "M", "L"],
    category: "Women"
  },
  {
    id: 11,
    name: "High-Rise Yoga Set",
    price: 4999,
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=2070&auto=format&fit=crop",
    description: "Seamless comfort meets performance. This matching set includes high-rise leggings and a supportive sports bra in moisture-wicking fabric designed for movement.",
    badge: { text: "New", bg: "bg-primary/90", color: "text-white" },
    rating: 4.9,
    reviews: 15,
    sizes: ["XS", "S", "M", "L"],
    category: "Women"
  },
   {
    id: 12,
    name: "Chelsea Leather Boots",
    price: 8999,
    originalPrice: 11999,
    image: "https://images.unsplash.com/photo-1608256246200-53e635b5b69f?q=80&w=1974&auto=format&fit=crop",
    description: "Rugged yet refined, these leather Chelsea boots feature elastic side panels and a durable rubber sole. The perfect footwear for transitional weather.",
    rating: 4.7,
    reviews: 103,
    sizes: ["8", "9", "10", "11", "12"],
    category: "Men"
  },
  // NEW ADDITIONS
  {
    id: 13,
    name: "Leather Crossbody Bag",
    price: 6999,
    originalPrice: 9999,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=2069&auto=format&fit=crop",
    description: "Elegant and practical, this leather crossbody bag features a compact design with multiple compartments. Finished with gold-tone hardware and an adjustable strap.",
    rating: 4.6,
    reviews: 54,
    sizes: ["One Size"],
    category: "Accessories"
  },
  {
    id: 14,
    name: "Kids' Denim Overalls",
    price: 2499,
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?q=80&w=2070&auto=format&fit=crop",
    description: "Classic denim overalls for active kids. Durable, comfortable, and featuring adjustable straps for a perfect fit as they grow.",
    rating: 4.8,
    reviews: 89,
    sizes: ["2T", "3T", "4T", "5T"],
    category: "Kids"
  },
  {
    id: 15,
    name: "Men's Aviator Sunglasses",
    price: 11999,
    originalPrice: 14999,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=2080&auto=format&fit=crop",
    description: "Timeless aviator style with polarized lenses. Lightweight metal frame ensures comfort for all-day wear while providing 100% UV protection.",
    badge: { text: "Classic", bg: "bg-gray-900", color: "text-white" },
    rating: 4.7,
    reviews: 210,
    sizes: ["One Size"],
    category: "Accessories"
  },
  {
    id: 16,
    name: "Knitted Wool Scarf",
    price: 3299,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=1974&auto=format&fit=crop",
    description: "Stay warm in style with this chunky knit wool scarf. Soft to the touch and long enough to wrap multiple times.",
    rating: 4.5,
    reviews: 45,
    sizes: ["One Size"],
    category: "Accessories"
  }
];

export const recommendedProducts: Product[] = [
    {
      id: 101,
      name: "Linen Resort Shirt",
      price: 2999,
      originalPrice: 3999,
      image: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=2070&auto=format&fit=crop",
      description: "Stay cool in our relaxed-fit linen shirt. Featuring a camp collar and a lightweight weave, it's the ultimate essential for warm weather getaways.",
      rating: 4.8,
      reviews: 67,
      sizes: ["S", "M", "L", "XL"],
      category: "Men"
    },
    {
      id: 102,
      name: "Structured Tote Bag",
      price: 6999,
      originalPrice: 9999,
      image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1935&auto=format&fit=crop",
      description: "A spacious everyday tote made from durable vegan leather. Includes multiple interior pockets for organization and a detachable shoulder strap.",
      badge: { text: "Staff Pick", bg: "bg-gray-900/90", color: "text-white" },
      rating: 4.9,
      reviews: 156,
      sizes: ["One Size"],
      category: "Accessories"
    },
    {
      id: 103,
      name: "Pleated Midi Skirt",
      price: 3299,
      originalPrice: 4999,
      image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=1964&auto=format&fit=crop",
      description: "Elegant and versatile, this midi skirt features permanent pleats and an elastic waistband for all-day comfort. Pairs perfectly with both heels and sneakers.",
      rating: 4.3,
      reviews: 42,
      sizes: ["XS", "S", "M", "L"],
      category: "Women"
    },
    {
      id: 104,
      name: "Modern Chino Shorts",
      price: 2299,
      originalPrice: 2999,
      image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=2070&auto=format&fit=crop",
      description: "Tailored from stretch-cotton twill, these shorts offer a clean look with the freedom to move. Finished with a garment dye for a soft, lived-in feel.",
      badge: { text: "-20% OFF", bg: "bg-red-500/90", color: "text-white" },
      rating: 4.6,
      reviews: 89,
      sizes: ["30", "32", "34", "36"],
      category: "Men"
    },
    {
      id: 105,
      name: "Canvas Weekender",
      price: 8499,
      originalPrice: 11999,
      image: "https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=2070&auto=format&fit=crop",
      description: "The ideal companion for short trips. Features a rugged canvas exterior, leather handles, and ample space for all your weekend essentials.",
      rating: 4.7,
      reviews: 112,
      sizes: ["One Size"],
      category: "Accessories"
    },
    {
      id: 106,
      name: "Minimalist Gold Watch",
      price: 15999,
      image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1999&auto=format&fit=crop",
      description: "Elegant simplicity. This gold-tone watch features a clean white dial, mesh strap, and precision Japanese quartz movement.",
      rating: 4.9,
      reviews: 28,
      sizes: ["One Size"],
      category: "Accessories"
    },
    {
      id: 107,
      name: "Silk Printed Scarf",
      price: 3499,
      image: "https://images.unsplash.com/photo-1601924994987-69e2c8e6f752?q=80&w=2070&auto=format&fit=crop",
      description: "Add a splash of color to any outfit with this 100% silk scarf. Features a hand-rolled hem and a vibrant, artistic abstract print.",
      rating: 4.4,
      reviews: 12,
      sizes: ["One Size"],
      category: "Accessories"
    },
    // NEW ADDITIONS
    {
        id: 108,
        name: "Floral Chiffon Blouse",
        price: 4299,
        originalPrice: 5999,
        image: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1974&auto=format&fit=crop",
        description: "Lightweight and airy, this chiffon blouse features a delicate floral print and balloon sleeves. Perfect for office wear or brunch dates.",
        rating: 4.4,
        reviews: 32,
        sizes: ["XS", "S", "M", "L"],
        category: "Women"
    },
    {
        id: 109,
        name: "Men's Performance Shorts",
        price: 2999,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=2071&auto=format&fit=crop",
        description: "Designed for training, these shorts are made from moisture-wicking fabric with 4-way stretch. Includes zippered pockets for essentials.",
        rating: 4.9,
        reviews: 156,
        sizes: ["S", "M", "L", "XL"],
        category: "Men"
    },
    {
        id: 110,
        name: "Leather Wallet",
        price: 3499,
        image: "https://images.unsplash.com/photo-1627123424574-181ce5171c98?q=80&w=1974&auto=format&fit=crop",
        description: "A slim bifold wallet crafted from genuine full-grain leather. Features RFID blocking technology to keep your cards safe.",
        rating: 4.8,
        reviews: 412,
        sizes: ["One Size"],
        category: "Accessories"
    },
    {
        id: 111,
        name: "Canvas Slip-On Shoes",
        price: 4299,
        originalPrice: 5499,
        image: "https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=2065&auto=format&fit=crop",
        description: "Casual comfort for everyday wear. These slip-on shoes feature a breathable canvas upper and a cushioned memory foam insole.",
        rating: 4.3,
        reviews: 98,
        sizes: ["7", "8", "9", "10", "11"],
        category: "Men"
    }
];

export const popularProducts: Product[] = [
    {
      id: 201,
      name: "Classic Denim Jacket",
      price: 6499,
      originalPrice: 8499,
      image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1887&auto=format&fit=crop",
      description: "A timeless classic. This denim jacket features a relaxed fit, durable cotton construction, and vintage-inspired hardware.",
      badge: { text: "Hot", bg: "bg-red-500/90", color: "text-white" },
      rating: 4.9,
      reviews: 342,
      sizes: ["S", "M", "L", "XL"],
      category: "Men"
    },
    {
      id: 202,
      name: "Everyday Chinos",
      price: 3499,
      originalPrice: 4999,
      image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1974&auto=format&fit=crop",
      description: "Versatile and comfortable, these chinos are designed for daily wear. Made with stretch cotton for ease of movement.",
      rating: 4.5,
      reviews: 128,
      sizes: ["30", "32", "34", "36"],
      category: "Men"
    },
    {
      id: 203,
      name: "White Leather Sneakers",
      price: 7499,
      originalPrice: 9999,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=2012&auto=format&fit=crop",
      description: "Minimalist design meets maximum comfort. These premium leather sneakers feature a cushioned sole and breathable lining.",
      badge: { text: "Limited", bg: "bg-gray-900/90", color: "text-white" },
      rating: 4.8,
      reviews: 215,
      sizes: ["8", "9", "10", "11"],
      category: "Men"
    },
    {
      id: 204,
      name: "Cashmere Sweater",
      price: 9499,
      originalPrice: 13999,
      image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1964&auto=format&fit=crop",
      description: "Luxuriously soft and warm. 100% Grade-A cashmere sweater with ribbed cuffs and hem.",
      rating: 5.0,
      reviews: 89,
      sizes: ["S", "M", "L"],
      category: "Women"
    },
    {
      id: 205,
      name: "Wayfarer Sunglasses",
      price: 11999,
      originalPrice: 15999,
      image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=2080&auto=format&fit=crop",
      description: "Iconic style with UV protection. Handcrafted frames with polarized lenses for superior clarity.",
      rating: 4.7,
      reviews: 456,
      sizes: ["One Size"],
      category: "Accessories"
    },
    {
      id: 206,
      name: "Wide Brim Fedora",
      price: 4299,
      originalPrice: 5999,
      image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?q=80&w=1887&auto=format&fit=crop",
      description: "Make a statement with this wool felt fedora. Features a wide stiff brim, a teardrop crown, and a grosgrain ribbon band.",
      badge: { text: "Trending", bg: "bg-accent/90", color: "text-white" },
      rating: 4.5,
      reviews: 67,
      sizes: ["S", "M", "L"],
      category: "Accessories"
    },
    {
      id: 207,
      name: "Merino Wool Beanie",
      price: 1999,
      image: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=1887&auto=format&fit=crop",
      description: "Essential for colder days. This chunky knit beanie is made from soft merino wool blend to keep you warm without itching.",
      rating: 4.8,
      reviews: 304,
      sizes: ["One Size"],
      category: "Accessories"
    },
    // NEW ADDITIONS
    {
        id: 208,
        name: "Statement Necklace",
        price: 4999,
        originalPrice: 7499,
        image: "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?q=80&w=1974&auto=format&fit=crop",
        description: "Elevate your evening look with this gold-plated statement necklace. Features geometric links and a secure lobster clasp.",
        rating: 4.6,
        reviews: 78,
        sizes: ["One Size"],
        category: "Accessories"
    },
    {
        id: 209,
        name: "Waterproof Hiking Boots",
        price: 10999,
        originalPrice: 13999,
        image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=1974&auto=format&fit=crop",
        description: "Conquer the trails with confidence. These waterproof boots offer superior ankle support and a high-traction outsole for rugged terrain.",
        badge: { text: "Durable", bg: "bg-green-600", color: "text-white" },
        rating: 4.9,
        reviews: 312,
        sizes: ["8", "9", "10", "11", "12"],
        category: "Men"
    },
    {
        id: 210,
        name: "Satin Midi Skirt",
        price: 3799,
        image: "https://images.unsplash.com/photo-1577900232427-18219b9166a3?q=80&w=1974&auto=format&fit=crop",
        description: "Luxurious satin finish with a flattering bias cut. This midi skirt adds a touch of glamour to any outfit.",
        rating: 4.5,
        reviews: 115,
        sizes: ["XS", "S", "M", "L"],
        category: "Women"
    },
    {
        id: 211,
        name: "Vintage Graphic Tee",
        price: 2199,
        image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?q=80&w=1887&auto=format&fit=crop",
        description: "Soft, washed cotton tee with a vintage-inspired graphic print. Relaxed fit for a cool, laid-back vibe.",
        rating: 4.7,
        reviews: 432,
        sizes: ["S", "M", "L", "XL"],
        category: "Women"
    },
    // New Kids Items
    {
        id: 301,
        name: "Kids' Puffer Jacket",
        price: 4299,
        originalPrice: 5999,
        image: "https://images.unsplash.com/photo-1519238809107-1e8787f185d5?q=80&w=2072&auto=format&fit=crop",
        description: "Keep them warm and stylish in this lightweight puffer jacket. Features a water-resistant shell and cozy insulation for cold days.",
        rating: 4.8,
        reviews: 62,
        sizes: ["3T", "4T", "5T", "6"],
        category: "Kids"
    },
    {
        id: 302,
        name: "Kids' Velcro Sneakers",
        price: 3299,
        image: "https://images.unsplash.com/photo-1514989940723-e8875ea6ab7d?q=80&w=2070&auto=format&fit=crop",
        description: "Easy-on, easy-off sneakers with velcro straps. Durable rubber soles and cushioned insoles make them perfect for active play.",
        rating: 4.6,
        reviews: 94,
        sizes: ["10K", "11K", "12K", "13K"],
        category: "Kids"
    }
];